server.port=8080
spring.data.mongodb.uri=mongodb+srv://quLY6H6ZuQdeTrtP:quLY6H6ZuQdeTrtP@mycluster1.wettq58.mongodb.net/journaldb?retryWrites=true&w=majority
spring.application.name=journalApp
spring.data.mongodb.database=journalDB

#JWT
jwt.secret=vG7pYxQ2k9N3rA5bZq1LwT8eDs4Hc0RuFfKjMiPn
jwt.expiration-ms=3600000    #1hr in ms